<a href="https://colab.research.google.com/github/Dehmaniyasmine/dashboard/blob/main/Classification_des_chiffres_manuscrits_de_la_base_de_donn%C3%A9es_MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
import tensorflow as tf
import keras
from sklearn import metrics

In [ ]:
from keras.datasets import mnist

In [ ]:
mnist.load_data()

((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [ ]:
from keras.datasets import mnist
from sklearn.model_selection import train_test_split

# Charger la base de données MNIST
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# Concaténer les données d'apprentissage et de test
X = np.concatenate((X_train, X_test))
y = np.concatenate((y_train, y_test))

# Diviser les données en ensembles d'apprentissage et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
from sklearn.svm import SVC
# Create and train SVM
X_train = X_train.reshape(-1, 28*28) /256
X_test = X_test.reshape(-1, 28*28) /256
svm_classifier = SVC(kernel='linear')
svm_classifier.fit(X_train, y_train)


SVC(kernel='linear')

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# ... (previous imports, data loading, reshaping, and training)

# Predict on test data
y_pred = svm_classifier.predict(X_test)

# Evaluate performance
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.935047619047619
              precision    recall  f1-score   support

           0       0.96      0.97      0.97      2058
           1       0.95      0.98      0.97      2364
           2       0.91      0.93      0.92      2133
           3       0.91      0.92      0.91      2176
           4       0.93      0.94      0.94      1936
           5       0.91      0.89      0.90      1915
           6       0.97      0.95      0.96      2088
           7       0.94      0.95      0.95      2248
           8       0.93      0.89      0.91      1992
           9       0.93      0.91      0.92      2090

    accuracy                           0.94     21000
   macro avg       0.93      0.93      0.93     21000
weighted avg       0.93      0.94      0.93     21000

[[2006    1   10    3    5   15   11    2    4    1]
 [   0 2323    5   12    1    5    0    7    8    3]
 [  13   22 1975   15   22    6   19   13   38   10]
 [  12   13   42 1998    4   46    2   20   22   17]
 

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
# Assuming you have X_test and y_test from your data loading and splitting

# ... (previous imports and model training)

# Predict on test data
y_pred = svm_classifier.predict(X_test)

# Assuming y_test is your true labels for the test set
y_true = y_test

# Evaluate performance
accuracy = accuracy_score(y_true, y_pred)
print(f"Accuracy: {accuracy}")
print(classification_report(y_true, y_pred))
print(confusion_matrix(y_true, y_pred))

Accuracy: 0.935047619047619
              precision    recall  f1-score   support

           0       0.96      0.97      0.97      2058
           1       0.95      0.98      0.97      2364
           2       0.91      0.93      0.92      2133
           3       0.91      0.92      0.91      2176
           4       0.93      0.94      0.94      1936
           5       0.91      0.89      0.90      1915
           6       0.97      0.95      0.96      2088
           7       0.94      0.95      0.95      2248
           8       0.93      0.89      0.91      1992
           9       0.93      0.91      0.92      2090

    accuracy                           0.94     21000
   macro avg       0.93      0.93      0.93     21000
weighted avg       0.93      0.94      0.93     21000

[[2006    1   10    3    5   15   11    2    4    1]
 [   0 2323    5   12    1    5    0    7    8    3]
 [  13   22 1975   15   22    6   19   13   38   10]
 [  12   13   42 1998    4   46    2   20   22   17]
 

In [ ]:
from sklearn.svm import SVC

# ... (previous imports, data loading, and reshaping)

# Create and train SVM with RBF kernel
svm_classifier = SVC(kernel='rbf')  # Changed to 'rbf'
svm_classifier.fit(X_train, y_train)

# ... (rest of your code for prediction and evaluation)

SVC()

In [ ]:
# Predict on test data
y_pred = svm_classifier.predict(X_test)

# Evaluate performance
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9762857142857143
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      2058
           1       0.98      0.99      0.99      2364
           2       0.97      0.98      0.97      2133
           3       0.97      0.97      0.97      2176
           4       0.97      0.98      0.97      1936
           5       0.98      0.97      0.97      1915
           6       0.98      0.99      0.99      2088
           7       0.97      0.97      0.97      2248
           8       0.98      0.96      0.97      1992
           9       0.97      0.96      0.97      2090

    accuracy                           0.98     21000
   macro avg       0.98      0.98      0.98     21000
weighted avg       0.98      0.98      0.98     21000

[[2035    1    3    0    1    4    8    2    4    0]
 [   0 2344    8    4    1    0    0    4    2    1]
 [   2    5 2083    5    5    4    6   13    8    2]
 [   2    2   19 2104    2   15    1   13   12    6]


In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Define the model
model = keras.Sequential(
    [
        keras.Input(shape=(28, 28, 1)), # Input layer
        layers.Conv2D(128, kernel_size=(3, 3), activation="relu"), # Convolutional layer with 128 filters
        layers.MaxPooling2D(pool_size=(2, 2)), # Max pooling layer
        layers.Flatten(), # Flatten layer to transition to dense layers
        layers.Dense(64, activation="relu"), # Hidden layer with 64 neurons
        layers.Dense(10, activation="softmax"), # Output layer with 10 neurons (for 10 digits)
    ]
)

# Compile the model
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
from tensorflow import keras
from sklearn.model_selection import train_test_split
import numpy as np

# Load MNIST dataset
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Concatenate training and test data
X = np.concatenate([x_train, x_test])
y = np.concatenate([y_train, y_test])

# Split into train and test sets (70/30 split)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Reshape the data to have a single channel
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1)

# Normalize pixel values to be between 0 and 1
X_train = X_train.astype('float32') / 255
X_test = X_test.astype('float32') / 255

# Convert labels to categorical (one-hot encoding)
y_train = keras.utils.to_categorical(y_train, num_classes=10)
y_test = keras.utils.to_categorical(y_test, num_classes=10)

print("MNIST dataset downloaded and split.")
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

MNIST dataset downloaded and split.
X_train shape: (49000, 28, 28, 1)
X_test shape: (21000, 28, 28, 1)
y_train shape: (49000, 10)
y_test shape: (21000, 10)


In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Define the CNN model
model = keras.Sequential(
    [
        keras.Input(shape=(28, 28, 1)),
        layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Flatten(),
        layers.Dropout(0.5),
        layers.Dense(10, activation="softmax"),
    ]
)

In [ ]:
# Compile the model
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
model.fit(X_train, y_train, batch_size=128, epochs=10, validation_split=0.1)

Epoch 1/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 39s 109ms/step - accuracy: 0.7289 - loss: 0.8617 - val_accuracy: 0.9704 - val_loss: 0.0976
Epoch 2/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 42s 114ms/step - accuracy: 0.9624 - loss: 0.1252 - val_accuracy: 0.9778 - val_loss: 0.0668
Epoch 3/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 41s 112ms/step - accuracy: 0.9724 - loss: 0.0896 - val_accuracy: 0.9841 - val_loss: 0.0570
Epoch 4/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 35s 96ms/step - accuracy: 0.9767 - loss: 0.0725 - val_accuracy: 0.9859 - val_loss: 0.0456
Epoch 5/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 45s 107ms/step - accuracy: 0.9806 - loss: 0.0615 - val_accuracy: 0.9886 - val_loss: 0.0410
Epoch 6/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 38s 97ms/step - accuracy: 0.9830 - loss: 0.0567 - val_accuracy: 0.9878 - val_loss: 0.0392
Epoch 7/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 42s 100ms/step - accuracy: 0.9841 - loss: 0.0508 - val_accuracy: 0.9869 - val_loss: 0.0423
Epoch 8/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 42s 104ms/step - accuracy: 0.9856 - loss: 0.0

In [ ]:
# Assuming you have your test data in 'X_test'
y_pred_probs = model.predict(X_test)  # Get predicted probabilities for each class

# Convert probabilities to class labels (highest probability)
y_pred_labels = np.argmax(y_pred_probs, axis=1)

657/657 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step


In [ ]:
y_test_multiclass = np.argmax(y_test, axis=1)

accuracy = accuracy_score(y_test_multiclass, y_pred_labels)
print(f"Accuracy: {accuracy}")

print(classification_report(y_test_multiclass, y_pred_labels))
print(confusion_matrix(y_test_multiclass, y_pred_labels))

Accuracy: 0.9880952380952381
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      2058
           1       0.99      0.99      0.99      2364
           2       0.98      0.99      0.98      2133
           3       0.99      0.99      0.99      2176
           4       0.99      0.98      0.99      1936
           5       0.99      0.99      0.99      1915
           6       0.99      0.99      0.99      2088
           7       0.99      0.98      0.99      2248
           8       0.99      0.97      0.98      1992
           9       0.97      0.99      0.98      2090

    accuracy                           0.99     21000
   macro avg       0.99      0.99      0.99     21000
weighted avg       0.99      0.99      0.99     21000

[[2042    0    3    0    0    1    4    2    2    4]
 [   0 2352    4    2    1    0    0    3    0    2]
 [   1    7 2107    2    0    0    1    9    1    5]
 [   1    0    6 2156    0    3    0    4    1    5]


In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1. Load and Preprocess Data
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Concatenate and split
X = np.concatenate([x_train, x_test])
y = np.concatenate([y_train, y_test])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Flatten and normalize
X_train = X_train.reshape(X_train.shape[0], -1).astype('float32') / 255
X_test = X_test.reshape(X_test.shape[0], -1).astype('float32') / 255

# One-hot encode labels
y_train = keras.utils.to_categorical(y_train, num_classes=10)
y_test = keras.utils.to_categorical(y_test, num_classes=10)

# 2. Define the MLP Model
model = keras.Sequential(
    [
        keras.Input(shape=(784,)),  # Input layer (784 features for flattened images)
        layers.Dense(512, activation="relu"),  # Hidden layer with 512 neurons
        layers.Dropout(0.2),  # Dropout for regularization
        layers.Dense(256, activation="relu"),  # Hidden layer with 256 neurons
        layers.Dropout(0.2),  # Dropout for regularization
        layers.Dense(10, activation="softmax"),  # Output layer with 10 neurons (for 10 digits)
    ]
)

# 3. Compile the Model
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

# 4. Train the Model
model.fit(X_train, y_train, batch_size=128, epochs=10, validation_split=0.1)

# 5. Predict Labels
y_pred_probs = model.predict(X_test)
y_pred_labels = np.argmax(y_pred_probs, axis=1)

# 6. Evaluate the Model
# Convert y_test to multiclass format for accuracy calculation
y_test_multiclass = np.argmax(y_test, axis=1)

accuracy = accuracy_score(y_test_multiclass, y_pred_labels)
print(f"Accuracy: {accuracy}")

print(classification_report(y_test_multiclass, y_pred_labels))
print(confusion_matrix(y_test_multiclass, y_pred_labels))

Epoch 1/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 9s 22ms/step - accuracy: 0.8425 - loss: 0.5421 - val_accuracy: 0.9602 - val_loss: 0.1268
Epoch 2/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - accuracy: 0.9607 - loss: 0.1324 - val_accuracy: 0.9749 - val_loss: 0.0845
Epoch 3/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 6s 18ms/step - accuracy: 0.9742 - loss: 0.0823 - val_accuracy: 0.9769 - val_loss: 0.0732
Epoch 4/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - accuracy: 0.9807 - loss: 0.0613 - val_accuracy: 0.9751 - val_loss: 0.0791
Epoch 5/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - accuracy: 0.9840 - loss: 0.0480 - val_accuracy: 0.9796 - val_loss: 0.0703
Epoch 6/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 9s 14ms/step - accuracy: 0.9863 - loss: 0.0418 - val_accuracy: 0.9814 - val_loss: 0.0625
Epoch 7/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 6s 18ms/step - accuracy: 0.9896 - loss: 0.0326 - val_accuracy: 0.9802 - val_loss: 0.0665
Epoch 8/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 9s 14ms/step - accuracy: 0.9918 - loss: 0.0271 - val_accu

In [ ]:
from sklearn.linear_model import SGDClassifier

# ... (previous imports, data loading, and reshaping)

# Create and train SGD classifier
sgd_classifier = SGDClassifier(random_state=42, loss='hinge')
sgd_classifier.fit(X_train, y_train_1d)  # Use y_train_1d here

# ... (rest of your code for prediction and evaluation)

SGDClassifier(random_state=42)

In [ ]:
# Predict on test data
y_pred = sgd_classifier.predict(X_test)  # Use sgd_classifier

# Evaluate performance
accuracy = accuracy_score(y_test_multiclass, y_pred)  # y_test_multiclass
print(f"Accuracy: {accuracy}")
print(classification_report(y_test_multiclass, y_pred))
print(confusion_matrix(y_test_multiclass, y_pred))

Accuracy: 0.9122380952380953
              precision    recall  f1-score   support

           0       0.96      0.97      0.97      2058
           1       0.95      0.98      0.96      2364
           2       0.92      0.88      0.90      2133
           3       0.89      0.89      0.89      2176
           4       0.91      0.90      0.91      1936
           5       0.90      0.85      0.87      1915
           6       0.94      0.95      0.94      2088
           7       0.93      0.93      0.93      2248
           8       0.86      0.87      0.86      1992
           9       0.86      0.89      0.87      2090

    accuracy                           0.91     21000
   macro avg       0.91      0.91      0.91     21000
weighted avg       0.91      0.91      0.91     21000

[[1996    2    6    2    6    7   19    4   14    2]
 [   0 2306   10   11    1   12    2    6   15    1]
 [  14   24 1884   36   29   10   27   32   62   15]
 [   4   13   43 1942    1   60   18   18   46   31]
